//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanLinhKienMayTinh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCao
    {
        public string MaQC { get; set; }
        public string TenQC { get; set; }
        public System.DateTime ThoiGianBatDau { get; set; }
        public System.DateTime ThoiGianKetThuc { get; set; }
        public string DuongDan { get; set; }
        public byte[] HinhAnh { get; set; }
        public string ViTri { get; set; }
    }
}
